export const MOVIES_LOAD_STARTED = 'MOVIES_LOAD_STARTED';
export const MOVIES_LOAD_SUCCESS = 'MOVIES_LOAD_SUCCESS';
export const MOVIES_LOAD_FAILURE = 'MOVIES_LOAD_FAILURE';

export const MOVIE_DELETE_STARTED = 'MOVIE_DELETE_STARTED';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_FAILURE = 'MOVIE_DELETE_FAILURE';

export const MOVIE_EDIT_STARTED = 'MOVIE_EDIT_STARTED';
export const MOVIE_EDIT_SUCCESS = 'MOVIE_EDIT_SUCCESS';
export const MOVIE_EDIT_FAILURE = 'MOVIE_EDIT_FAILURE';

export const MOVIE_ADD_STARTED = 'MOVIE_ADD_STARTED';
export const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS';
export const MOVIE_ADD_FAILURE = 'MOVIE_ADD_FAILURE';

export const FILTER_MOVIES = 'FILTER_MOVIES';
export const SORT_MOVIES = 'SORT_MOVIES';

export const MOVIES_SEARCH_STARTED = 'MOVIES_SEARCH_STARTED';
export const MOVIES_SEARCH_SUCCESS = 'MOVIES_SEARCH_SUCCESS';
export const MOVIES_SEARCH_FAILURE = 'MOVIES_SEARCH_FAILURE';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
